Word_Dictionary = {
"of":"a","with":"a","within":"a","to":"a","done":"Ad","they":"Af","you":"Af","yes":"Ai",
"will":"An","shall":"An","will have done":"Anad","shall have done":"Anad","will do":"Anad","industry":"Ang","manufacturing":"Ang",
"domain":"Ankor","realm":"Ankor","country":"Ankor","soon":"Anu","very soon":"Anu","to be":"Arm","was":"Urz","axe":"Az","war axe":"Az",
"treasure":"Azgal","hoard":"Azgal","wealth":"Azgal","masonry":"Azkahr","silver":"Azril","metal":"Azul",
"gate":"Barak","door":"Barak","war machine":"Barag","artillery":"Barag","bond":"Baraz","oath":"Baraz","promise":"Baraz",
"own":"Bezek","possess":"Bezek","owner":"Bezeki","possessor":"Bezeki","in a":"Bin","on":"Bin","beside":"Bin","oh":"Boga",
"ah":"Bok","miner":"Boki","fat":"Bolg","affluent":"Bolg","clever":"Bran","alert":"Bran","cunning":"Bran",
"bread":"Brog","cake":"Brog","gold":"Bryn","crystal":"Brynduraz","cheese":"Chuf","sturdy":"Dal",
"grudge":"Dammaz","bitterness":"Dammaz","bitter":"Dammaz","great book of grudges":"Dammaz Kron","grudge book":"Dammaz Kron",
"bet":"Dar","wager":"Dar","challenge":"Dar","head":"Dawazbak","dwarf":"Dawi","dwarves":"Dawi","dwarfs":"Dawi",
"reliable":"Dawr","untested":"Deb","unconditioned":"Deb","unreliable":"Deb","obvious":"Doh","observe":"Dok","watch":"Dok","eye":"Dok",
"balls":"Dongliz","dragon":"Drakk","long distance":"Drek","ambition":"Drek","kill":"Dreng","slay":"Dreng","slayer":"Drengi",
"trap door":"Dringorak","thunder":"Dron","boom":"Dron","loud noise":"Dron","defeat":"Drung","vanquish":"Drung","cramped":"Duk",
"doom":"Dum","darkness":"Dum","chaos":"Dum","stone":"Duraz","hard":"Durak","staircase":"Ekrund",
"elf":"Elgi","elfs":"Elgi","elves":"Elgi","weak":"Elgram","thin":"Elgram","feeble":"Elgram","half-arsed":"Elgraz",
"engineer":"Endrinkuli","mechanic":"Endrinkuli","mushroom":"Frongol","oathgold":"Galbaraz",
"find":"Gand","discover":"Gand","fearless":"Garaz","rebellious":"Garaz","wastland":"Gazan","plains":"Gazan",
"dying oath":"Gazul Bar Baraz","skull":"Ghal","mess":"Gibal","annoying":"Ginit","tunnel":"Girt",
"to go":"Git","went":"Ged","old":"Gnol","trustworthy":"Gnol","wise":"Gnol","respect":"Gnoll-engrom",
"wild":"Gor","beast":"Gor","uncanny":"Gorak","yellow":"Gorl","beer":"Gorog","ale":"Gorog",
"march":"Got","travel":"Got","neck pain":"Grik","harsh":"Grim","unyielding":"Grim","barren":"Grimaz","empty":"Grimaz",
"steel":"Grimazul","plait":"Grindal","waste":"Grint","lean meat":"Grizal","vintage":"Grizdal","green":"Grob",
"golbin":"Grobi","goblins":"Grobi","goblin":"Grobi","evil":"Grobkaz","nasty":"Grobkaz","slaughter":"Grobkul","brave":"Grom","defiant":"Grom",
"ancient":"Gromdal","ancestor":"Gromthi","anvil":"Grong","to do":"Gronit","have done":"Grird","did":"Grird","giant":"Gronti",
"whine":"Grumbak","complaint":"Grumbak","grumble":"Grumbak","whiner":"Grumbaki","complainer":"Grumbaki","grumbler":"Grumbaki",
"hammer":"Grund","morse code":"Grundlid","morse-code":"Grundlid","mine":"Grung","making":"Grungnaz","smithing":"Grungnaz",
"forge":"Grungron","guzzle":"Guz","rash":"Hazkal","horn":"Hirn","burden":"Hunk","eugh":"Ik","eww":"Ik","ew":"Ik","pillar":"Irkul",
"copper":"Izor","pass":"Kadrin","volcano":"Karag","mountail":"Karak",
"eternal":"Karaz","capital":"Karaz","citadel":"Karaz","everlasting":"Karaz","enduring":"Karaz","fortress":"Kazad",
"war":"Kazak","battle":"Kazak","conflict":"Kazak","hall":"Khaz","drum":"Khrum","armour":"Klad","chisel":"Klinka","carving":"Klinkarun",
"black":"Kol","nose":"Konk","book":"Kron","record":"Kron","chronicle":"Kron","unexpected":"Kruk","disaster":"Krunk",
"disease":"Krut","illness":"Krut","diseased":"Kruti","sickly":"Kruti","stew":"Kuri","lady":"Kvinn","tongue":"Lid",
"intricate":"Lok","embellished":"Lok","praiseworthy":"Lok","tool":"Makaz","weapon":"Makaz","splitter":"Maraz","break":"Maraz",
"watchtower":"Mingol","ogre":"Ogri","ogres":"Ogri","skillfull":"Ok","craftsman":"Okri","comrad":"Onk","friend":"Onk","dirt":"Onk",
"uncomfortable":"Ragarin","coarse":"Ragarin","rune":"Rhun","word":"Rhun","words":"Rhun","runes":"Rhun","runelord":"Rhunki","runesmith":"Rhunki",
"lord":"Rik","king":"Rik","woman":"Rinn","women":"Rinn","dome":"Ruff","brawl":"Runk","thrashing":"Runk","diarrhea":"Rutz",
"blue":"Skarrenruf","thief":"Skaz","scavenge":"Skrat","poor":"Skrati","rock-fall":"Skree","scrawny":"Skruff","unkept":"Skruff","hard-working":"Skrund",
"scuffle":"Skuf","skirmish":"Skuf","sludge":"Slotch","strike":"Stok","hit":"Stok","walk":"Strol","strol":"Strol","stream":"Stromez",
"murder":"Thag","betrayal":"Thag","murderer":"Thagi","murderers":"Thagi","skaven":"Thaggoraki","secret":"Thrindrongol",
"forest":"Thingaz","army":"Throng","clan":"Throng","gun":"Thrund","musket":"Thrund","rifle":"Thrund","beard":"Tromm","hello":"Tromm","hi":"Tromm",
"vain":"Ufdi","roughly":"Umanar","approximately":"Umanar","about":"Umanar","shoddy":"Umgak","unstable":"Umgak","men":"Umgi","humans":"Umgi",
"oathbreaker":"Unbaraki","oathbreakers":"Unbaraki","liar":"Unbaraki","liars":"Unbaraki","watchpost":"Und","underway":"Ungdrin",
"cave":"Ungor","cavern":"Ungor","untrustworthy":"Ungrim","trade":"Urbar","market":"Urbaz","ork":"Urk","bones":"Uzkul","death":"Uzkul",
"brewery":"Valdahaz","lake":"Varn","sea":"Varr","raiders":"Vongal","farm":"Vorn","disreputable":"Wanaz",
"unsuccessfull":"Wattock","faliour":"Wattock","stupid":"Wazzok ","foolish":"Wazzok ","gullible":"Wazzok ","naive":"Wazzok ","confused":"Werit",
"wood":"wut","oak":"Wutroth","white":"Wyr","isolated":"Zak","crazy":"Zaki","crazed":"Zaki","madman":"Zaki","tooth":"Zahn","fang":"Zahn",
"vampire":"Zangunaz","vampires":"Zangunaz","blood":"Zan","red":"Zan","fire":"Zharr",
"torrent":"Zhuf","waterfall":"Zhuf","river":"Zhuf","plateau":"Zorn","sun":"Zon","iron":"Zul"
}

letter_dictionary = {
'a':'ᚨ','b':'ᛒ','c':'ᚲ','d':'ᛞ','e':'ᛖ','f':'ᚠ','g':'ᚷ','h':'ᚺ','i':'ᛁ','j':'ᛃ','k':'ᚲ','l':'ᛚ','m':'ᛗ','n':'ᚾ','o':'ᛟ','p':'ᛈ','q':'ᛟ','r':'ᚱ','s':'ᛊ','t':'ᛏ','u':'ᚢ','v':'ᚢ','w':'ᚹ','x':'ᛉ','y':'ᛇ','z':'ᛉ',
'A':'ᚨ','B':'ᛒ','C':'ᚲ','D':'ᛞ','E':'ᛖ','F':'ᚠ','G':'ᚷ','H':'ᚺ','I':'ᛁ','J':'ᛃ','K':'ᚲ','L':'ᛚ','M':'ᛗ','N':'ᚾ','O':'ᛟ','P':'ᛈ','Q':'ᛟ','R':'ᚱ','S':'ᛊ','T':'ᛏ','U':'ᚢ','V':'ᚢ','W':'ᚹ','X':'ᛉ','Y':'ᛇ','Z':'ᛉ'
}

symbols = {"!","\"","£","$","%","^","&","*","(",")","-","+","=","\\","`","\[","\]",";","\'","@","#","~","<",",",">",".","?","/","|"}
